const rawStudents = [
  { rollNo: "23SS1A0501", name: "ABDUL AHAD", gender: "M" },
  { rollNo: "23SS1A0502", name: "ANURADHA KUMARI JHA", gender: "F" },
  { rollNo: "23SS1A0503", name: "ARRAMONI ARAVIND", gender: "M" },
  { rollNo: "23SS1A0504", name: "ARUTLA ETTI HARSHINI", gender: "F" },
  { rollNo: "23SS1A0505", name: "AZMEERA MANJU", gender: "F" },
  { rollNo: "23SS1A0506", name: "BALLARAPU ABHISHA", gender: "F" },
  { rollNo: "23SS1A0507", name: "BATANA RAVINDRANATH", gender: "M" },
  { rollNo: "23SS1A0508", name: "BEKKANTI VISHWAS", gender: "M" },
  { rollNo: "23SS1A0509", name: "BHUTHAM SRIKANTH", gender: "M" },
  { rollNo: "23SS1A0510", name: "BOINAPALLI MIDILESH VARDHAN", gender: "M" },
  { rollNo: "23SS1A0511", name: "BOLLI HARIKA", gender: "F" },
  { rollNo: "23SS1A0512", name: "BYRRAJU NAREN VARMA", gender: "M" },
  { rollNo: "23SS1A0513", name: "CHADUVULA MITHIL REDDY", gender: "M" },
  { rollNo: "23SS1A0514", name: "DAMMU PRAVEEN KUMAR", gender: "M" },
  { rollNo: "23SS1A0515", name: "DARA PRAKSHITH KUMAR", gender: "M" },
  { rollNo: "23SS1A0516", name: "DARA SINDHUJA", gender: "F" },
  { rollNo: "23SS1A0517", name: "DASARI SAI PRASANNA", gender: "F" },
  { rollNo: "23SS1A0518", name: "GANDAMALLA ANJALI", gender: "F" },
  { rollNo: "23SS1A0519", name: "GANGAVATH MANEESHA", gender: "F" },
  { rollNo: "23SS1A0520", name: "GHANAPURAM DHARANI", gender: "F" },
  { rollNo: "23SS1A0521", name: "GOLLA MEENA BHAVANI", gender: "F" },
  { rollNo: "23SS1A0522", name: "GOLLA SAI TEJA", gender: "M" },
  { rollNo: "23SS1A0523", name: "GOPAGONI RENUKA", gender: "F" },
  { rollNo: "23SS1A0524", name: "GUDURU LAXMI NIHAL VARMA", gender: "M" },
  { rollNo: "23SS1A0525", name: "GUGULOTH HIMAVARSHINI", gender: "F" },
  { rollNo: "23SS1A0526", name: "GURRALA THANSHITHA", gender: "F" },
  { rollNo: "23SS1A0527", name: "KAKANI SAI SATHISH", gender: "M" },
  { rollNo: "23SS1A0528", name: "KANAKARAJU SUDHA", gender: "F" },
  { rollNo: "23SS1A0529", name: "KARNE VISHWANATH", gender: "M" },
  { rollNo: "23SS1A0530", name: "KARRI ENOSH", gender: "M" },
  { rollNo: "23SS1A0531", name: "KASOJU POOJITHA", gender: "F" },
  { rollNo: "23SS1A0532", name: "KODEM AJAY RAGHAVA", gender: "M" },
  { rollNo: "23SS1A0533", name: "KOLICHELMA BINDU SRI", gender: "F" },
  { rollNo: "23SS1A0534", name: "KOLUVULA ANIL KUMAR", gender: "M" },
  { rollNo: "23SS1A0535", name: "KONAM VENKAT ASRITH", gender: "M" },
  { rollNo: "23SS1A0536", name: "KONGARI NAKSHITHA", gender: "F" },
  { rollNo: "23SS1A0537", name: "KOVAGANI JAYASRAVAN", gender: "M" },
  { rollNo: "23SS1A0538", name: "LAGALA VARUN", gender: "M" },
  { rollNo: "23SS1A0539", name: "LODE SANKEERTHANA", gender: "F" },
  { rollNo: "23SS1A0540", name: "MALOTH SINDHUSHA", gender: "F" },
  { rollNo: "23SS1A0541", name: "MARA NIVEDITHA", gender: "F" },
  { rollNo: "23SS1A0542", name: "MUDAVATH RAJESH", gender: "M" },
  { rollNo: "23SS1A0543", name: "MULA VARSHITH REDDY", gender: "M" },
  { rollNo: "23SS1A0544", name: "MUNJAM SAI KIRAN", gender: "M" },
  { rollNo: "23SS1A0545", name: "NAKKA BHARATH CHANDRA", gender: "M" },
  { rollNo: "23SS1A0546", name: "NIMMANAGOTI RAJARJESHWARI", gender: "F" },
  { rollNo: "23SS1A0547", name: "PAGIDIPALA KEERTHI", gender: "F" },
  { rollNo: "23SS1A0548", name: "PAMMI KOMALI KAVYA", gender: "F" },
  { rollNo: "23SS1A0549", name: "PAWAR AMRUTH", gender: "M" },
  { rollNo: "23SS1A0550", name: "PENDELA SUNNY", gender: "M" },
  { rollNo: "23SS1A0551", name: "RACHURI ANILKUMAR", gender: "M" },
  { rollNo: "23SS1A0552", name: "REKHANDAR SHARATH CHANDRA", gender: "M" },
  { rollNo: "23SS1A0553", name: "RENIKUNTA HARINI", gender: "F" },
  { rollNo: "23SS1A0554", name: "SARVANI LAXMI PRASANNA", gender: "F" },
  { rollNo: "23SS1A0555", name: "SHAIK ABBU SOFIYAN", gender: "M" },
  { rollNo: "23SS1A0556", name: "SHAIK AFREEN", gender: "F" },
  { rollNo: "23SS1A0557", name: "SILIVERU ABHILASH", gender: "M" },
  { rollNo: "23SS1A0558", name: "SUREPALLY UMA MAHESHWARI", gender: "F" },
  { rollNo: "23SS1A0559", name: "SURYAWANSHI LOKESH GIRISH", gender: "M" },
  { rollNo: "23SS1A0560", name: "THAGULLA HARSHITH SAIKUMAR", gender: "M" },
  { rollNo: "23SS1A0561", name: "THANGALLAPALLI RAHITHYA", gender: "F" },
  { rollNo: "23SS1A0562", name: "VADATHYA JAIRAM", gender: "M" },
  { rollNo: "23SS1A0563", name: "VADLA GOVARDHAN", gender: "M" },
  { rollNo: "23SS1A0564", name: "VAISHNAVI GURRAMKONDA", gender: "F" },
  { rollNo: "23SS1A0565", name: "VANARASI GOURI", gender: "F" },
  { rollNo: "23SS1A0566", name: "VETTI OOHA SRI", gender: "F" }
];

const facultyMembers = [
  {
    facultyId: "FAC-CSE-001",
    name: "Dr. K. Srinivas Rao",
    designation: "Professor & HOD",
    department: "Computer Science & Engineering",
    email: "faculty@college.edu",
    phone: "+91 98490 12345",
    office: "Room 401, CSE Block",
    experience: "18 Years",
    subjects: ["AI & Machine Learning", "Cloud Computing"]
  },
  {
    facultyId: "FAC-CSE-002",
    name: "Mrs. P. Anitha",
    designation: "Associate Professor",
    department: "Computer Science & Engineering",
    email: "anitha.cse@college.edu",
    phone: "+91 98490 67890",
    office: "Room 405, CSE Block",
    experience: "12 Years",
    subjects: ["Full Stack Web Dev", "DevOps & Microservices"]
  },
  {
    facultyId: "FAC-CSE-003",
    name: "Mr. M. Rajesh",
    designation: "Assistant Professor",
    department: "Computer Science & Engineering",
    email: "rajesh.cse@college.edu",
    phone: "+91 94401 54321",
    office: "Room 408, CSE Block",
    experience: "8 Years",
    subjects: ["Cyber Security & Cryptography", "Big Data Analytics"]
  }
];

const subjectsList = [
  { code: "CS701PC", name: "Cloud Computing", department: "CSE", year: "IV Year", semester: "I Sem (7th)", credits: 4 },
  { code: "CS702PC", name: "Artificial Intelligence & Machine Learning", department: "CSE", year: "IV Year", semester: "I Sem (7th)", credits: 4 },
  { code: "CS703PE", name: "DevOps & Microservices Architecture", department: "CSE", year: "IV Year", semester: "I Sem (7th)", credits: 3 },
  { code: "CS704PE", name: "Cyber Security & Cryptography", department: "CSE", year: "IV Year", semester: "I Sem (7th)", credits: 3 },
  { code: "CS705OE", name: "Full Stack Web Development", department: "CSE", year: "IV Year", semester: "I Sem (7th)", credits: 3 },
  { code: "CS711PC", name: "Cloud Computing & AI/ML Laboratory", department: "CSE", year: "IV Year", semester: "I Sem (7th)", credits: 2 },
  { code: "CS801PC", name: "Major Project / Dissertation", department: "CSE", year: "IV Year", semester: "II Sem (8th)", credits: 10 },
  { code: "CS802PE", name: "Big Data Analytics & Distributed Systems", department: "CSE", year: "IV Year", semester: "II Sem (8th)", credits: 3 }
];

module.exports = {
  rawStudents,
  facultyMembers,
  subjectsList
};
